name: tyba_university_explorer
description: A new Flutter project for Tyba technical test.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.3.0

  # State Management
  provider: ^6.0.5

  # Dependency Injection (Service Locator)
  get_it: ^7.6.0

  # Value equality (ayuda a comparar objetos en los modelos)
  equatable: ^2.0.5

  # Imagenes y UI
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing (Mocking library sencilla)
  mocktail: ^1.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true